### PR TITLE
Added options for Sqlite backend

### PR DESCRIPTION
**Pull request by pbv**
Hello, 
I've added some options to allow using the Snap.Auth.Sqlite backend; maybe you'd like review these and merge them into your repository.

### CODE REVIEW

**Review by dzhus — CHANGES_REQUESTED** [review]
Hey, thanks for the patch, I'm going to ask you to put in a few lines in `README.md` too to document this (as it no longer supports only JSON)

**Comment by pbv** [comment]
Before I do that let me point out that I did a quick hack and changed the options semantics slightly: instead of `-j file` you need to use  `-j -f file` (for Json) or `-s -f file` (for Sqlite). I couldn't figure a way to parsing an enumeration with fields using implicit arguments and didn't want to rewrite the option parsing using a lower level library. 
This may break existing scripts; if you're OK with this I'll modify the README.

**Comment by dzhus** [comment]
@pbv Of course, the change makes sense, and I think it's perfectly fine as long as it's documented. I'll use this as a chance to start a CHANGELOG too.

**Comment by pbv** [comment]
OK, I've updated the README file.

**Comment by dzhus** [comment]
@pbv Did you find an issue or was the PR closed by accident?

**Comment by pbv** [comment]
Sorry, my mistake

**Review by dzhus — APPROVED** [review]

**Comment by dzhus** [comment]
@pbv This has now been pushed to Hackage as 0.2

**Pull request merged**
